name: lahma
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.8+1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  intl: ^0.16.0
  data_connection_checker: ^0.3.4
  flushbar: 1.9.1
  flutter_phoenix: "^0.1.0"
  google_maps_flutter: ^0.5.26+2
  flutter_rating_bar: ^3.0.1+1
  share: ^0.6.4
  firebase_auth: ^0.16.0
  cached_network_image: ^2.1.0+1
  geolocator: ^5.3.1
  path_provider: ^1.6.7
  flutter_google_places: ^0.2.4
  sqflite: ^1.3.0
  back_button_interceptor: ^4.2.3
  permission_handler: ^5.0.0+hotfix.3
  google_maps_place_picker: ^0.9.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/locale/localization_en.json
    - assets/locale/localization_ar.json
    - assets/images/logo.png
    - assets/images/page-bg-pattern.png
    - assets/images/navbar_icon1.png
    - assets/images/navbar_icon2.png
    - assets/images/navbar_icon3.png
    - assets/images/navbar_icon4.png
    - assets/images/pattern-bottom-left.png
    - assets/images/pattern-top-right.png
    - assets/images/front-page-image-bottom.png
    - assets/images/cart-icon.png
    - assets/images/home-banner.png
    - assets/images/back-icon.png
    - assets/images/checkbox-active.png
    - assets/images/checkbox-not-active.png
    - assets/images/delete-icon.png
    - assets/images/location-icon.png
    - assets/images/location-icon-colored.png
    - assets/images/pro1.png
    - assets/images/pro2.png
    - assets/images/search-icon.png
    - assets/images/Layer1.png
    - assets/images/Layer2.png
    - assets/images/Layer3.png
    - assets/images/Layer4.png
    - assets/images/Layer2_red.png 
    - assets/images/Layer3_red.png
    - assets/images/Layer4_red.png
    - assets/images/envelope-icon.png
    - assets/images/close-icon.png
    - assets/images/help-icon.png
    - assets/images/share1.png
    - assets/images/share2.png
    - assets/images/share3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
